version: "2"
services:
  
  nodejs-app:
    image: 917411321124.dkr.ecr.ap-south-1.amazonaws.com/node-app-repo:latest
    container_name: nodejs-app
    ports:
      - 5000:5000
    environment:
      #MONGO_URI: mongodb://mongodb:27017/library
      - MONGO_URI=mongodb://mongodb:27017/library
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    restart: always
    
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379

