version: '3'

services:
  web:
    image: 917411321124.dkr.ecr.ap-south-1.amazonaws.com/node-app-repo:latest
    container_name: nodejs-app
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
