version: "2"
services:
  
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - 5000:5000
    environment:
      #MONGO_URI: mongodb://mongodb:27017/library
      - MONGO_URI=mongodb://mongodb:27017/library
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - db:/data/db
      
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  db:
